version: '3.8'

services:
    db_dev:
        image: postgres:alpine3.18
        restart: always
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        ports:
            - 5432:5432
        networks:
            shop_network:

networks:
    shop_network:
